### ISSUE TITLE
MedSci Workflow: Authorization list for access to MSL GPS Zone

### ISSUE THREAD

**Issue by wwelling** [TAMULib/fw-registry#101]
Perl script (ringle:/export/home/voyager/scripts/ms/grad_access.pl) that extracts uin/id_card and other data for grad/professional students in schools/majors served by MedSci for input into card reader system to allow access to GPS Zone.

**Comment by hismith** [comment]
[gps.sql.txt](https://github.com/TAMULib/fw-registry/files/6599315/gps.sql.txt)

**Comment by hismith** [comment]
Uploaded gps.sql file contains current criteria for this extract. Robin Sewell needs to receive the output from this report by Monday 6/28 so that she can prep for the re-opening of the zone on 7/5. This could be done as an email attachment (current method) or could be a file that she downloads from the "scaffolding" from the new mis that will replace voyager mis and contain folio ldp.
